project_id = "mxsotxddcvmeluqonuuj"

[functions.ai-lead-scoring]
verify_jwt = false

[functions.ai-sales-assistant]
verify_jwt = false

[functions.send-slack-notification]
verify_jwt = false

[functions.shopify-config]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.shopify-order-processor]
verify_jwt = false

[functions.shopify-order-backfill]
verify_jwt = false

[functions.shopify-monitor]
verify_jwt = false