-- Append new columns at the end (CREATE OR REPLACE VIEW cannot reorder existing columns).
DROP VIEW IF EXISTS public.unified_lead_feed CASCADE;

CREATE VIEW public.unified_lead_feed AS
SELECT 'website'::text AS source,
    l.id::text AS source_row_id,
    COALESCE(NULLIF(l.name, ''::text), NULL::text) AS name,
    NULLIF(l.phone, ''::text) AS phone,
    NULLIF(l.email, ''::text) AS email,
    NULLIF(l.company, ''::text) AS company,
    "left"(COALESCE(NULLIF(l.subject, ''::text), NULLIF(l.message, ''::text)), 500) AS subject_or_message,
    COALESCE(NULLIF(l.status, ''::text), 'new'::text) AS status,
    l.assigned_to AS sales_person_id,
    NULLIF(l.assigned_to_name, ''::text) AS sales_person_name,
    l.assigned_to IS NOT NULL AS is_assigned,
    l.created_at,
    'leads'::text AS source_table,
    COALESCE(l.disposition::text, 'untouched') AS disposition,
    l.disposition_reason_code,
    l.disposition_reason_note,
    l.disposition_at,
    l.disposition_by_name
FROM leads l
UNION ALL
SELECT 'forms'::text,
    f.id::text,
    COALESCE(NULLIF(f.customer_name, ''::text), NULL::text),
    NULLIF(f.phone, ''::text),
    NULLIF(f.email, ''::text),
    COALESCE(NULLIF(f.company, ''::text), NULL::text),
    "left"(COALESCE(NULLIF(f.product_name, ''::text), NULLIF(f.notes, ''::text), NULLIF(f.form_name, ''::text)), 500),
    COALESCE(NULLIF(f.status, ''::text), 'new'::text),
    COALESCE(f.sales_person_id, f.assigned_to),
    COALESCE(NULLIF(f.sales_person_name, ''::text), NULLIF(f.assigned_to_name, ''::text)),
    COALESCE(f.sales_person_id, f.assigned_to) IS NOT NULL,
    f.created_at,
    'form_leads'::text,
    COALESCE(f.disposition::text, 'untouched'),
    f.disposition_reason_code,
    f.disposition_reason_note,
    f.disposition_at,
    f.disposition_by_name
FROM form_leads f
UNION ALL
SELECT 'google_ads'::text,
    g.id::text,
    COALESCE(NULLIF(g.customer_name, ''::text), NULL::text),
    NULLIF(g.phone, ''::text),
    NULLIF(g.email, ''::text),
    COALESCE(NULLIF(g.customer_company, ''::text), NULL::text),
    "left"(COALESCE(NULLIF(g.product_name, ''::text), NULLIF(g.notes, ''::text), NULLIF(g.campaign_name, ''::text)), 500),
    COALESCE(NULLIF(g.status, ''::text), 'new'::text),
    g.sales_person_id,
    NULLIF(g.sales_person_name, ''::text),
    g.sales_person_id IS NOT NULL,
    g.created_at,
    'google_ads_leads'::text,
    COALESCE(g.disposition::text, 'untouched'),
    g.disposition_reason_code,
    g.disposition_reason_note,
    g.disposition_at,
    g.disposition_by_name
FROM google_ads_leads g
UNION ALL
SELECT 'interakt'::text,
    i.id::text,
    COALESCE(NULLIF(i.customer_name, ''::text), NULL::text),
    NULLIF(i.phone_number, ''::text),
    NULLIF(i.email, ''::text),
    COALESCE(NULLIF(i.company, ''::text), NULLIF(i.customer_company, ''::text)),
    "left"(COALESCE(NULLIF(i.product_name, ''::text), NULLIF(i.notes, ''::text), NULLIF(i.source, ''::text)), 500),
    COALESCE(NULLIF(i.status, ''::text), 'new'::text),
    CASE WHEN i.sales_person_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'::text THEN i.sales_person_id::uuid ELSE NULL::uuid END,
    NULLIF(i.sales_person_name, ''::text),
    i.sales_person_id IS NOT NULL AND i.sales_person_id <> ''::text,
    i.created_at,
    'interakt_leads'::text,
    COALESCE(i.disposition::text, 'untouched'),
    i.disposition_reason_code,
    i.disposition_reason_note,
    i.disposition_at,
    i.disposition_by_name
FROM interakt_leads i
UNION ALL
SELECT 'myoperator'::text,
    c.id::text,
    COALESCE(NULLIF(c.customer_name, ''::text), NULLIF(c.agent_name, ''::text), NULLIF(c.caller_number, ''::text)),
    COALESCE(NULLIF(c.caller_number, ''::text), NULLIF(c.full_number, ''::text)),
    NULLIF(c.email, ''::text),
    COALESCE(NULLIF(c.customer_company, ''::text), NULLIF(c.company, ''::text)),
    "left"(COALESCE(NULLIF(c.requirement, ''::text), NULLIF(c.notes, ''::text), NULLIF(c.product_name, ''::text), NULLIF(c.call_status, ''::text)), 500),
    COALESCE(NULLIF(c.lead_status, ''::text), NULLIF(c.call_status, ''::text), 'new'::text),
    COALESCE(c.sales_person_id, c.assigned_to),
    COALESCE(NULLIF(c.sales_person_name, ''::text), NULLIF(c.assigned_to_name, ''::text), NULLIF(c.assigned_agent_name, ''::text)),
    COALESCE(c.sales_person_id, c.assigned_to) IS NOT NULL,
    c.created_at,
    'call_logs'::text,
    COALESCE(c.disposition::text, 'untouched'),
    c.disposition_reason_code,
    c.disposition_reason_note,
    c.disposition_at,
    c.disposition_by_name
FROM call_logs c
WHERE c.lead_source IS DISTINCT FROM 'ElevenLabs'::text
UNION ALL
SELECT 'elevenlabs'::text,
    c.id::text,
    COALESCE(NULLIF(c.customer_name, ''::text), NULLIF(c.caller_number, ''::text)),
    COALESCE(NULLIF(c.caller_number, ''::text), NULLIF(c.full_number, ''::text)),
    NULLIF(c.email, ''::text),
    COALESCE(NULLIF(c.customer_company, ''::text), NULLIF(c.company, ''::text)),
    "left"(COALESCE(NULLIF(c.requirement, ''::text), NULLIF(c.notes, ''::text), NULLIF(c.raw_transcript, ''::text)), 500),
    COALESCE(NULLIF(c.lead_status, ''::text), NULLIF(c.call_status, ''::text), 'new'::text),
    COALESCE(c.sales_person_id, c.assigned_to),
    COALESCE(NULLIF(c.sales_person_name, ''::text), NULLIF(c.assigned_to_name, ''::text)),
    COALESCE(c.sales_person_id, c.assigned_to) IS NOT NULL,
    c.created_at,
    'call_logs'::text,
    COALESCE(c.disposition::text, 'untouched'),
    c.disposition_reason_code,
    c.disposition_reason_note,
    c.disposition_at,
    c.disposition_by_name
FROM call_logs c
WHERE c.lead_source = 'ElevenLabs'::text
UNION ALL
SELECT 'email'::text,
    e.id::text,
    COALESCE(NULLIF(e.customer_name, ''::text), NULL::text),
    NULLIF(e.phone_number, ''::text),
    NULLIF(e.email, ''::text),
    COALESCE(NULLIF(e.customer_company, ''::text), NULL::text),
    "left"(COALESCE(NULLIF(e.subject, ''::text), NULLIF(e.notes, ''::text), NULLIF(e.body_text, ''::text)), 500),
    COALESCE(NULLIF(e.status, ''::text), 'new'::text),
    e.sales_person_id,
    NULLIF(e.sales_person_name, ''::text),
    e.sales_person_id IS NOT NULL,
    e.created_at,
    'email_leads'::text,
    COALESCE(e.disposition::text, 'untouched'),
    e.disposition_reason_code,
    e.disposition_reason_note,
    e.disposition_at,
    e.disposition_by_name
FROM email_leads e;

GRANT SELECT ON public.unified_lead_feed TO authenticated, anon, service_role;