-- =====================================================
-- Make GRN sequence access explicit
-- =====================================================
-- public.generate_grn_number() is a BEFORE INSERT trigger on goods_receipts and
-- is deliberately NOT security definer, so nextval('grn_number_seq') executes
-- with the privileges of whoever is inserting.
--
-- This is a no-op on the current database: `authenticated` already holds
-- USAGE + SELECT on the sequence via Supabase's default privileges for new
-- objects in public, which this project has not narrowed.
--
-- It is here so GRN numbering does not silently depend on that default. Locking
-- down public default privileges is a common hardening step, and the failure it
-- would cause is easy to misread: RLS passes, then the trigger fires and the
-- sequence read is refused, so it surfaces as
--
--   permission denied for sequence grn_number_seq
--
-- on insert rather than as a policy failure.
--
-- Drop this migration if you would rather not carry a defensive no-op.
GRANT USAGE, SELECT ON SEQUENCE public.grn_number_seq TO authenticated;
GRANT ALL ON SEQUENCE public.grn_number_seq TO service_role;
