ALTER TABLE public.abandoned_carts
  ADD COLUMN IF NOT EXISTS recovered_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS recovered_amount NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS recovery_source TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS auto_email_1_sent_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS auto_email_2_sent_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS auto_email_3_sent_at TIMESTAMPTZ DEFAULT NULL;