export const DEPARTMENT_OPTIONS = [
  'Procurement',
  'Operations',
  'Finance / Accounts',
  'Sales',
  'Marketing',
  'Engineering',
  'R&D',
  'IT',
  'HR',
  'Admin',
  'Production',
  'Quality',
  'Logistics',
  'Customer Support',
  'Founder / Leadership',
];

export const DESIGNATION_OPTIONS = [
  'Founder',
  'Co-Founder',
  'CEO',
  'COO',
  'CTO',
  'CFO',
  'Director',
  'VP',
  'General Manager',
  'Senior Manager',
  'Manager',
  'Assistant Manager',
  'Team Lead',
  'Senior Engineer',
  'Engineer',
  'Procurement Officer',
  'Purchase Manager',
  'Operations Head',
  'Accountant',
  'Sales Executive',
  'Account Executive',
  'Owner',
  'Partner',
  'Consultant',
];

export const CITY_OPTIONS = [
  'Mumbai',
  'Delhi',
  'Bengaluru',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Pune',
  'Ahmedabad',
  'Gurgaon',
  'Noida',
  'Jaipur',
  'Surat',
  'Lucknow',
  'Chandigarh',
  'Indore',
  'Bhopal',
  'Nagpur',
  'Coimbatore',
  'Kochi',
  'Visakhapatnam',
  'Goa',
  'Thane',
  'Faridabad',
  'Ghaziabad',
];